export const  currencies = [
  { value: "USD", label: "USD - US Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British Pound" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "AUD", label: "AUD - Australian Dollar" },

  { value: "AFN", label: "AFN - Afghan Afghani" },
  { value: "ALL", label: "ALL - Albanian Lek" },
  { value: "DZD", label: "DZD - Algerian Dinar" },
  { value: "AOA", label: "AOA - Angolan Kwanza" },
  { value: "ARS", label: "ARS - Argentine Peso" },
  { value: "AMD", label: "AMD - Armenian Dram" },
  { value: "AWG", label: "AWG - Aruban Florin" },
  { value: "AZN", label: "AZN - Azerbaijani Manat" },
  { value: "BSD", label: "BSD - Bahamian Dollar" },
  { value: "BHD", label: "BHD - Bahraini Dinar" },
  { value: "BDT", label: "BDT - Bangladeshi Taka" },
  { value: "BBD", label: "BBD - Barbadian Dollar" },
  { value: "BYN", label: "BYN - Belarusian Ruble" },
  { value: "BZD", label: "BZD - Belize Dollar" },
  { value: "XOF", label: "XOF - West African CFA Franc" },
  { value: "BMD", label: "BMD - Bermudian Dollar" },
  { value: "BTN", label: "BTN - Bhutanese Ngultrum" },
  { value: "BOB", label: "BOB - Boliviano" },
  { value: "BAM", label: "BAM - Bosnia & Herzegovina Convertible Mark" },
  { value: "BWP", label: "BWP - Botswana Pula" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "BND", label: "BND - Brunei Dollar" },
  { value: "BGN", label: "BGN - Bulgarian Lev" },
  { value: "KHR", label: "KHR - Cambodian Riel" },
  { value: "CNY", label: "CNY - Chinese Yuan Renminbi" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "CRC", label: "CRC - Costa Rican Colón" },
  { value: "CUP", label: "CUP - Cuban Peso" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "EGP", label: "EGP - Egyptian Pound" },
  { value: "FJD", label: "FJD - Fijian Dollar" },
  { value: "GHS", label: "GHS - Ghana Cedi" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "HUF", label: "HUF - Hungarian Forint" },
  { value: "ISK", label: "ISK - Icelandic Krona" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "IRR", label: "IRR - Iranian Rial" },
  { value: "ILS", label: "ILS - Israeli New Shekel" },
  { value: "JOD", label: "JOD - Jordanian Dinar" },
  { value: "KZT", label: "KZT - Kazakhstani Tenge" },
  { value: "KES", label: "KES - Kenyan Shilling" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "KWD", label: "KWD - Kuwaiti Dinar" },
  { value: "LAK", label: "LAK - Lao Kip" },
  { value: "LBP", label: "LBP - Lebanese Pound" },

  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "LRD", label: "LRD - Liberian Dollar" },
  { value: "LYD", label: "LYD - Libyan Dinar" },
  { value: "MOP", label: "MOP - Macanese Pataca" },
  { value: "MKD", label: "MKD - Macedonian Denar" },
  { value: "MGA", label: "MGA - Malagasy Ariary" },
  { value: "MWK", label: "MWK - Malawian Kwacha" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "MVR", label: "MVR - Maldivian Rufiyaa" },
  { value: "MCF", label: "MCF - Mauritian Rupee" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "MDL", label: "MDL - Moldovan Leu" },
  { value: "MNT", label: "MNT - Mongolian Tugrik" },
  { value: "MAD", label: "MAD - Moroccan Dirham" },
  { value: "MZN", label: "MZN - Mozambican Metical" },
  { value: "NAD", label: "NAD - Namibian Dollar" },
  { value: "NPR", label: "NPR - Nepalese Rupee" },
  { value: "TWD", label: "TWD - New Taiwan Dollar" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "NIO", label: "NIO - Nicaraguan Córdoba" },
  { value: "NGN", label: "NGN - Nigerian Naira" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "OMR", label: "OMR - Omani Rial" },
  { value: "PKR", label: "PKR - Pakistani Rupee" },
  { value: "PEN", label: "PEN - Peruvian Sol" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "PLN", label: "PLN - Polish Zloty" },
  { value: "QAR", label: "QAR - Qatari Rial" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "RWF", label: "RWF - Rwandan Franc" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "RSD", label: "RSD - Serbian Dinar" },
  { value: "SCR", label: "SCR - Seychelles Rupee" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "SHP", label: "SHP - Saint Helena Pound" },
  { value: "SLL", label: "SLL - Sierra Leonean Leone" },
  { value: "SOS", label: "SOS - Somali Shilling" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "SSP", label: "SSP - South Sudanese Pound" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
  { value: "SDG", label: "SDG - Sudanese Pound" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "SRD", label: "SRD - Surinamese Dollar" },
  { value: "SYP", label: "SYP - Syrian Pound" },
  { value: "TZS", label: "TZS - Tanzanian Shilling" },
];


export const countries = [
  { value: "US", label: "United States" },
  { value: "CA", label: "Canada" },
  { value: "GB", label: "United Kingdom" },
  { value: "DE", label: "Germany" },
  { value: "FR", label: "France" },
  { value: "AU", label: "Australia" },
  { value: "JP", label: "Japan" },
  { value: "IN", label: "India" },
  { value: "BR", label: "Brazil" },
  { value: "MX", label: "Mexico" },

  // additional 50
  { value: "AF", label: "Afghanistan" },
  { value: "AL", label: "Albania" },
  { value: "DZ", label: "Algeria" },
  { value: "AO", label: "Angola" },
  { value: "AR", label: "Argentina" },
  { value: "AM", label: "Armenia" },
  { value: "AZ", label: "Azerbaijan" },
  { value: "BH", label: "Bahrain" },
  { value: "BD", label: "Bangladesh" },
  { value: "BB", label: "Barbados" },
  { value: "BY", label: "Belarus" },
  { value: "BE", label: "Belgium" },
  { value: "BZ", label: "Belize" },
  { value: "BJ", label: "Benin" },
  { value: "BT", label: "Bhutan" },
  { value: "BO", label: "Bolivia" },
  { value: "BA", label: "Bosnia & Herzegovina" },
  { value: "BW", label: "Botswana" },
  { value: "BG", label: "Bulgaria" },
  { value: "BF", label: "Burkina Faso" },
  { value: "BI", label: "Burundi" },
  { value: "KH", label: "Cambodia" },
  { value: "CM", label: "Cameroon" },
  { value: "CV", label: "Cape Verde" },
  { value: "CF", label: "Central African Republic" },
  { value: "TD", label: "Chad" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colombia" },
  { value: "CR", label: "Costa Rica" },
  { value: "CI", label: "Côte d’Ivoire" },
  { value: "HR", label: "Croatia" },
  { value: "CU", label: "Cuba" },
  { value: "CY", label: "Cyprus" },
  { value: "CZ", label: "Czech Republic" },
  { value: "DK", label: "Denmark" },
  { value: "DO", label: "Dominican Republic" },
  { value: "EC", label: "Ecuador" },
  { value: "EG", label: "Egypt" },
  { value: "SV", label: "El Salvador" },
  { value: "GQ", label: "Equatorial Guinea" },
  { value: "ER", label: "Eritrea" },
  { value: "EE", label: "Estonia" },
  { value: "ET", label: "Ethiopia" },
  { value: "FJ", label: "Fiji" },
  { value: "FI", label: "Finland" },
  { value: "GA", label: "Gabon" },
  { value: "GM", label: "Gambia" },
  { value: "GE", label: "Georgia" }
];
